// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace devsko.LayoutAnalyzer
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string PackageString = "512c11db-6dde-43c1-9a10-d8aa821444e2";
        public static Guid Package = new Guid(PackageString);

        public const string CommandSetString = "d18f8b78-d4ab-4bc2-bc4e-bb6ed891ee2f";
        public static Guid CommandSet = new Guid(CommandSetString);

        public const string OutputWindowPaneString = "a19b6446-f4a7-4a70-86f3-93a03b38f335";
        public static Guid OutputWindowPane = new Guid(OutputWindowPaneString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int LayoutWindowCommand = 0x0100;
    }
}