// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace devsko.LayoutAnalyzer
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidPackageString = "512c11db-6dde-43c1-9a10-d8aa821444e2";
        public static Guid guidPackage = new Guid(guidPackageString);

        public const string guidLayoutAnalyzerPackageCmdSetString = "d18f8b78-d4ab-4bc2-bc4e-bb6ed891ee2f";
        public static Guid guidLayoutAnalyzerPackageCmdSet = new Guid(guidLayoutAnalyzerPackageCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyCommand = 0x0100;
    }
}
